#version 450


#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
#if HLSLCC_ENABLE_UNIFORM_BUFFERS
#define UNITY_UNIFORM
#else
#define UNITY_UNIFORM uniform
#endif
#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
#if UNITY_SUPPORTS_UNIFORM_LOCATION
#define UNITY_LOCATION(x) layout(location = x)
#define UNITY_BINDING(x) layout(binding = x, std140)
#else
#define UNITY_LOCATION(x)
#define UNITY_BINDING(x) layout(std140)
#endif
uniform 	vec4 _ProjectionParams;
uniform 	vec4 hlslcc_mtx4x4unity_MatrixV[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	float _CrestLodAlphaBlackPointFade;
uniform 	float _CrestLodAlphaBlackPointWhitePointFade;
uniform 	vec4 _CrestLodInstanceData[14];
uniform 	float Shore_maxPixelsToShoreline;
uniform 	float Shore_maxShallowDepth;
uniform 	float Shore_shallowDepthOffset;
uniform 	float Shore_gerstnerWavelength;
uniform 	float Shore_gerstnerParallelity;
uniform 	float Shore_gerstnerSpeed;
uniform 	float Shore_gerstnerAmplitude;
uniform 	float Shore_gerstnerSteepness;
uniform 	vec2 Shore_windDirection;
uniform 	vec4 _ShorelineOffsetScale;
UNITY_BINDING(0) uniform UnityPerDraw {
	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
	vec4 hlslcc_mtx4x4unity_WorldToObject[4];
	vec4 unity_LODFade;
	mediump vec4 unity_WorldTransformParams;
	vec4 unity_RenderingLayer;
	vec4 unity_ProbesOcclusion;
	mediump vec4 unity_SpecCube0_HDR;
	vec4 unity_SpecCube0_BoxMax;
	vec4 unity_SpecCube0_BoxMin;
	vec4 unity_SpecCube0_ProbePosition;
	vec4 unity_LightmapST;
	vec4 unity_DynamicLightmapST;
	vec4 unity_LightmapColorDir;
	mediump vec4 unity_SHAr;
	mediump vec4 unity_SHAg;
	mediump vec4 unity_SHAb;
	mediump vec4 unity_SHBr;
	mediump vec4 unity_SHBg;
	mediump vec4 unity_SHBb;
	mediump vec4 unity_SHC;
};
UNITY_BINDING(1) uniform _NshmGlobal {
	mediump vec4 _EnvColor;
	mediump vec4 _AmbientColor;
	mediump vec4 _EnvStrength;
	mediump vec4 _SceneLightGlobalParams;
	mediump vec4 _DielectricSpecOverride;
	mediump vec4 _DefaultSpecCube_HDR;
	mediump vec4 _WindDirection;
	mediump vec4 _WindGlobal;
	vec3 _SkySunDir;
	float _VegetationWindSwitch;
	mediump vec4 ambient_SH[3];
	mediump vec4 ambientChar_SH[7];
	mediump vec4 ambientCharSkin_SH[7];
	mediump vec4 _TerrainLightMapColorScale;
	mediump vec4 _TerrainLightMapColorBias;
	mediump vec4 _TerrainHeightmapBlendScale;
	mediump vec4 _CharacterAOSpecularParam;
	mediump vec4 _GlobalMipBias;
	vec4 _TerrainHeightmapRecipSize;
	vec4 _TerrainHeightmapScale;
	vec4 VTTerrainSize;
	vec4 VTTerainCacheSize;
	vec4 VTPageTableSize;
	vec4 _StreamAnchorPosHeightmap;
	vec4 _TerrainSize;
	vec4 topLeftUVHeightmap[4];
	vec4 _LightTextureAABBMin;
	mediump vec4 g_AtmosphereLightDirection;
	mediump vec4 g_CameraAerialPerspectiveVolumeParam;
	mediump vec4 g_CameraAerialPerspectiveVolumeParam2;
	mediump vec4 _CharacterShadowGlobalParam;
	int pangu_LightmapConfig;
	int _LightmapBaseConfig;
	int overridePropsMaxIndex;
	int _DisableDynamicShadow;
	float _PreWaterDepthSign;
	mediump float _ObjectFresnelIntensity;
	mediump float _NoBakedAmbientScale;
	mediump float _TerrainBlendDistance;
	mediump float _FakeBlendMaskBuff[16];
	int _MaxLightmapMipLevel;
};
UNITY_BINDING(2) uniform UnityPerMaterial {
	mediump float _NormalsStrength;
	mediump float _NormalsScale;
	mediump float _NormalScrollStrength;
	mediump vec3 _Diffuse;
	mediump vec3 _DiffuseGrazing;
	mediump vec3 _BackWaterColor;
	mediump float _ShadowStrength;
	mediump float _NoiseIntensityX;
	mediump float _NoiseIntensityY;
	mediump vec3 _SubSurfaceColour;
	mediump float _SubSurfaceBase;
	mediump float _SubSurfaceSun;
	mediump float _SubSurfaceSunFallOff;
	mediump float _SubSurfaceHeightPower;
	mediump float _HGParam;
	mediump float _SubSurfaceDepthMax;
	mediump float _SubSurfaceDepthPower;
	float _ReflectionStrength;
	mediump float _Specular;
	mediump float _SpecularPower;
	mediump float _SpecularIntensity;
	mediump float _SpecularFlickerScale;
	mediump vec4 _SpecularFlickerPower;
	mediump vec4 _SpecularPowerVaryParam;
	mediump float _ReflectionBlur;
	mediump float _FresnelPower;
	mediump float _LightIntensityMultiplier;
	float _RefractiveIndexOfAir;
	float _RefractiveIndexOfWater;
	mediump float _PlanarReflectionNormalsStrength;
	mediump float _PlanarReflectionIntensity;
	float _SSRNormalDistort;
	float _FoamScale;
	vec4 _FoamTexture_TexelSize;
	mediump vec4 _FoamWhiteColor;
	mediump vec4 _FoamBubbleColor;
	mediump float _FoamBubbleParallax;
	mediump float _ShorelineFoamMinDepth;
	mediump float _WaveFoamFeather;
	mediump float _WaveFoamBubblesCoverage;
	mediump float _WaveFoamNormalStrength;
	mediump float _WaveFoamSpecularFallOff;
	mediump float _WaveFoamSpecularBoost;
	mediump float _RefractionStrength;
	mediump vec4 _DepthFogDensity;
	mediump float _TransparencyVal;
	mediump float _TransparencyCurve;
	mediump float _TransparencyReflEdge;
	mediump float _CausticsTextureScale;
	mediump float _CausticsTextureAverage;
	mediump float _CausticsStrength;
	mediump float _CausticsFocalDepth;
	mediump float _CausticsDepthOfField;
	mediump float _CausticsEdgeSmooth;
	mediump float _CausticsDistortionScale;
	mediump float _CausticsDistortionStrength;
	mediump float _CausticsDepthLimit;
	float _NormalsMinScale;
	int _InstanceStartLocation;
	float _DispSampleTile;
	float _DispHeightScale;
	float _DispChoppyScale;
	float _BaseNormalStrength;
	uint _LD_SliceIndex;
	mediump float _WaveFoamLightScale;
	mediump float _SpecularFarScale;
	mediump float _WaterBrushColorBrightness;
	mediump float _NormalYint;
	mediump float _ShorelineNoiseScale;
	mediump float _ShorelineNoiseStrength;
	mediump float _ShorelinePreview;
	mediump vec4 _TranslucencyColor;
	mediump float _TranslucencyStrength;
	mediump float _TranslucencyExp;
	mediump float _UnderWaterRefractionStrength;
};
UNITY_BINDING(3) uniform CrestPerMaterial {
	int _ShallowColorGradientLength;
	mediump vec4 _ShallowColors[4];
	mediump float _SubSurfaceHeightMax;
	mediump vec3 _SubSurfaceCrestColour;
	mediump vec2 _WindDirXZ;
	float _HeightOffset;
	vec4 _JitterDiameters_CurrentFrameWeights;
	vec3 _CenterPos;
	vec3 _Scale;
	vec4 hlslcc_mtx4x4_MainCameraProjectionMatrix[4];
	float _FoamFadeRate;
	float _WaveFoamStrength;
	float _WaveFoamCoverage;
	float _ShorelineFoamMaxDepth;
	float _ShorelineFoamStrength;
	float _SimDeltaTime;
	float _SimDeltaTimePrev;
	float _LODChange;
	mediump float _Damping;
	vec2 _LaplacianAxisX;
	mediump float _Gravity;
	mediump vec4 _UnderWaterGradientColor[4];
	int _UnderWaterGradientColorCount;
	mediump float _UnderWaterGradientColorMaxDepth;
	mediump float _UnderWaterGradientColorDepthPower;
	mediump vec4 _customLightDiretion;
	mediump float _WaterBrushColorBrightCoef;
	uint _FFTWaveParam;
	mediump vec3 _DynWaveColor;
	mediump float _DynWaveColorStrength;
	mediump float _DynWaveHeightMinVal;
	vec3 _DynWaveSequenceCenter_Range;
	vec2 _DynWaveSequenceDir;
	vec4 _LD_Params[7];
	vec3 _LD_Pos_Scale[7];
	vec4 _LD_Params_Source[7];
	vec3 _LD_Pos_Scale_Source[7];
	uint _LD_SliceIndex_Source;
};
UNITY_BINDING(4) uniform CrestPerFrame {
	float _CrestTime;
	vec3 _OceanCenterPosWorld;
	float _TexelsPerWave;
	float _CurrentOceanScale;
	float _CrestGlobalAlpha;
	float _ForceUnderwater;
	vec4 _DisplaceMapValMin;
	vec4 _DisplaceMapValRange;
	vec4 _FFTChoppyFactor;
	vec4 _FFTGridSizes;
	vec4 _FFTHeightMin;
	vec4 _FFTHeightRange;
	vec4 _FFTChoppyMin;
	vec4 _FFTChoppyRange;
	vec4 _FFTGradient0Min;
	vec4 _FFTGradient0Range;
	vec4 _FFTGradient1Min;
	vec4 _FFTGradient1Range;
	vec4 _FFTFoam0Min;
	vec4 _FFTFoam0Range;
	vec4 _FFTFoam1Min;
	vec4 _FFTFoam1Range;
};
UNITY_LOCATION(11) uniform mediump sampler2D _ShoreLineMap;
in mediump vec3 in_POSITION0;
layout(location = 0) out highp vec4 vs_TEXCOORD0;
layout(location = 1) out highp vec4 vs_TEXCOORD1;
layout(location = 2) out highp vec4 vs_TEXCOORD2;
layout(location = 5) out highp vec3 vs_TEXCOORD3;
layout(location = 3) out highp vec3 vs_TEXCOORD4;
layout(location = 6) out highp vec3 vs_TEXCOORD5;
layout(location = 4) out highp vec2 vs_TEXCOORD8;
vec4 u_xlat0;
int u_xlati0;
vec4 u_xlat1;
bvec2 u_xlatb1;
vec4 u_xlat2;
uint u_xlatu2;
bvec2 u_xlatb2;
vec4 u_xlat3;
bool u_xlatb3;
vec4 u_xlat4;
vec3 u_xlat5;
vec3 u_xlat6;
vec3 u_xlat7;
vec3 u_xlat8;
bool u_xlatb8;
vec2 u_xlat9;
vec2 u_xlat10;
float u_xlat12;
vec2 u_xlat13;
vec2 u_xlat14;
bvec2 u_xlatb14;
vec2 u_xlat15;
float u_xlat19;
float u_xlat21;
void main()
{
    u_xlati0 = int(_LD_SliceIndex) << 1;
    u_xlat6.xyz = in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz;
    u_xlat6.xyz = hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx + u_xlat6.xyz;
    u_xlat6.xyz = hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz + u_xlat6.xyz;
    u_xlat0.yzw = u_xlat6.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz;
    u_xlat1.x = _CrestLodInstanceData[u_xlati0].z + _CrestLodInstanceData[u_xlati0].z;
    u_xlat7.x = 4.0 * _CrestLodInstanceData[u_xlati0].z;
    u_xlat13.xy = hlslcc_mtx4x4unity_ObjectToWorld[3].xz / u_xlat1.xx;
    u_xlat13.xy = fract(u_xlat13.xy);
    u_xlat1.xz = (-u_xlat13.xy) * u_xlat1.xx + u_xlat0.yw;
    u_xlat2.xy = u_xlat1.xz + (-vec2(_OceanCenterPosWorld.x, _OceanCenterPosWorld.z));
    u_xlat19 = max(abs(u_xlat2.y), abs(u_xlat2.x));
    u_xlatu2 = _LD_SliceIndex;
    u_xlat19 = u_xlat19 / _LD_Pos_Scale[int(u_xlatu2)].z;
    u_xlat19 = u_xlat19 + -1.0;
    u_xlat19 = u_xlat19 + (-_CrestLodAlphaBlackPointFade);
    u_xlat19 = u_xlat19 / _CrestLodAlphaBlackPointWhitePointFade;
    u_xlat19 = max(u_xlat19, 0.0);
    u_xlat0.x = u_xlat19 + _CrestLodInstanceData[u_xlati0].x;
    u_xlat0.x = min(u_xlat0.x, 1.0);
    u_xlat2.xy = u_xlat1.xz / u_xlat7.xx;
    u_xlat2.xy = fract(u_xlat2.xy);
    u_xlat2.xy = u_xlat2.xy + vec2(-0.5, -0.5);
    u_xlatb14.xy = lessThan(abs(u_xlat2.xyxy), vec4(0.25999999, 0.25999999, 0.25999999, 0.25999999)).xy;
    u_xlat2.xy = u_xlat0.xx * u_xlat2.xy;
    u_xlat7.xz = u_xlat2.xy * u_xlat7.xx + u_xlat1.xz;
    u_xlat0.y = (u_xlatb14.x) ? u_xlat7.x : u_xlat1.x;
    u_xlat0.w = (u_xlatb14.y) ? u_xlat7.z : u_xlat1.z;
    u_xlat1.xy = u_xlat0.yw + (-_TerrainSize.zw);
    u_xlat13.xy = u_xlat1.xy * _TerrainSize.yy;
    u_xlat1.xy = u_xlat1.xy + (-_ShorelineOffsetScale.xy);
    u_xlat1.xy = u_xlat1.xy * _TerrainSize.yy;
    u_xlat1.xy = u_xlat1.xy * _TerrainSize.xx;
    vs_TEXCOORD8.xy = u_xlat1.xy * _ShorelineOffsetScale.zw;
    u_xlatb1.xy = lessThan(u_xlat13.xyxx, vec4(0.0, 0.0, 0.0, 0.0)).xy;
    u_xlatb2.xy = lessThan(vec4(1.0, 1.0, 0.0, 0.0), u_xlat13.xyxx).xy;
    u_xlatb1.x = u_xlatb1.x || u_xlatb2.x;
    u_xlatb1.x = u_xlatb1.y || u_xlatb1.x;
    u_xlatb1.x = u_xlatb2.y || u_xlatb1.x;
    if(!u_xlatb1.x){
        u_xlat1 = textureLod(_ShoreLineMap, u_xlat13.xy, 0.0);
        u_xlatb2.x = u_xlat1.z>=1.0;
        u_xlatb8 = -0.99000001>=u_xlat1.z;
        u_xlatb2.x = u_xlatb8 || u_xlatb2.x;
        if(!u_xlatb2.x){
            u_xlat19 = u_xlat1.w * Shore_maxShallowDepth;
            u_xlat2 = u_xlat1.zzxy * vec4(2.0, 2.0, 2.0, 2.0) + vec4(-0.699999988, -1.0, -1.0, -1.0);
            u_xlat1.x = u_xlat2.y * Shore_maxPixelsToShoreline;
            u_xlat7.x = (-u_xlat2.y) + 1.0;
            u_xlat7.x = clamp(u_xlat7.x, 0.0, 1.0);
            u_xlat13.x = Shore_gerstnerWavelength * 0.5 + u_xlat19;
            u_xlat13.x = u_xlat13.x * 0.5;
            u_xlat13.x = clamp(u_xlat13.x, 0.0, 1.0);
            u_xlatb3 = u_xlat19>=Shore_shallowDepthOffset;
            u_xlat3.x = u_xlatb3 ? 1.0 : float(0.0);
            u_xlat3.x = u_xlat7.x * u_xlat3.x;
            u_xlat2.x = u_xlat2.x;
            u_xlat2.x = clamp(u_xlat2.x, 0.0, 1.0);
            u_xlat2.x = u_xlat7.x * u_xlat2.x;
            u_xlat2.x = u_xlat13.x * u_xlat2.x;
            u_xlat9.x = 6.28318548 / Shore_gerstnerWavelength;
            u_xlat9.x = u_xlat9.x * Shore_gerstnerSpeed;
            u_xlat9.x = u_xlat9.x * _CrestTime;
            u_xlat15.x = dot(vec2(Shore_windDirection.x, Shore_windDirection.y), u_xlat0.yw);
            u_xlat15.x = (-u_xlat2.y) * Shore_maxPixelsToShoreline + u_xlat15.x;
            u_xlat15.x = u_xlat15.x * Shore_gerstnerParallelity;
            u_xlat8.x = u_xlat2.y * Shore_maxPixelsToShoreline + u_xlat15.x;
            u_xlat8.x = u_xlat8.x / Shore_gerstnerWavelength;
            u_xlat14.xy = vec2(Shore_windDirection.x, Shore_windDirection.y) * vec2(9.99999997e-07, 9.99999997e-07) + (-u_xlat2.zw);
            u_xlat21 = Shore_gerstnerParallelity * Shore_gerstnerParallelity;
            u_xlat4.xy = (-u_xlat14.xy) + vec2(Shore_windDirection.x, Shore_windDirection.y);
            u_xlat14.xy = vec2(u_xlat21) * u_xlat4.xy + u_xlat14.xy;
            u_xlat21 = dot(u_xlat14.xy, u_xlat14.xy);
            u_xlat21 = inversesqrt(u_xlat21);
            u_xlat14.xy = u_xlat14.xy * vec2(u_xlat21);
            u_xlat1.x = u_xlat15.x * 3.0 + u_xlat1.x;
            u_xlat1.x = u_xlat1.x / Shore_gerstnerWavelength;
            u_xlat15.x = u_xlat9.x * 0.5;
            u_xlat1.x = u_xlat1.x * 6.28318548 + u_xlat15.x;
            u_xlat1.x = u_xlat1.x * 0.370370358;
            u_xlat1.x = cos(u_xlat1.x);
            u_xlat1.x = u_xlat1.x * 0.5 + 0.5;
            u_xlat15.xy = u_xlat0.yw * vec2(0.5, 0.5);
            u_xlat15.xy = u_xlat15.xy / vec2(vec2(Shore_gerstnerWavelength, Shore_gerstnerWavelength));
            u_xlat15.xy = vec2(_CrestTime) * vec2(0.300000012, 0.400000006) + u_xlat15.xy;
            u_xlat15.xy = sin(u_xlat15.xy);
            u_xlat15.x = u_xlat15.x * 0.25;
            u_xlat15.x = u_xlat15.x * u_xlat15.y + 0.75;
            u_xlat7.x = u_xlat13.x * u_xlat7.x;
            u_xlat1.x = u_xlat1.x * u_xlat7.x;
            u_xlat1.x = u_xlat15.x * u_xlat1.x;
            u_xlat1.x = u_xlat1.x * Shore_gerstnerAmplitude;
            u_xlat7.xy = u_xlat1.xx * vec2(0.5, 1.20000005);
            u_xlat19 = u_xlat1.x * 2.55999994 + u_xlat19;
            u_xlat19 = u_xlat19 / Shore_gerstnerAmplitude;
            u_xlat19 = clamp(u_xlat19, 0.0, 1.0);
            u_xlat8.x = u_xlat8.x * 6.28318548 + u_xlat9.x;
            u_xlat4.x = sin(u_xlat8.x);
            u_xlat5.x = cos(u_xlat8.x);
            u_xlat9.xy = u_xlat14.xy * u_xlat5.xx;
            u_xlat9.xy = u_xlat9.xy * vec2(Shore_gerstnerSteepness);
            u_xlat10.xy = u_xlat14.xy * u_xlat4.xx;
            u_xlat10.xy = u_xlat1.xx * u_xlat10.xy;
            u_xlat10.xy = vec2(u_xlat19) * u_xlat10.xy;
            u_xlat10.xy = u_xlat10.xy + u_xlat10.xy;
            u_xlat9.xy = u_xlat9.xy * u_xlat1.xx + (-u_xlat10.xy);
            u_xlat8.x = u_xlat8.x + 0.157079637;
            u_xlat8.x = u_xlat8.x * 0.159154937;
            u_xlat8.x = fract(u_xlat8.x);
            u_xlat14.xy = u_xlat14.xy * u_xlat7.xx;
            u_xlat7.xz = vec2(u_xlat19) * u_xlat14.xy;
            u_xlat14.x = u_xlat8.x * 10.0;
            u_xlat14.x = min(u_xlat14.x, 1.0);
            u_xlat8.x = u_xlat8.x * 10.0 + -1.0;
            u_xlat8.x = clamp(u_xlat8.x, 0.0, 1.0);
            u_xlat8.x = (-u_xlat8.x) + u_xlat14.x;
            u_xlat5.xz = (-u_xlat7.xz) * u_xlat8.xx + u_xlat9.xy;
            u_xlat5.y = u_xlat4.x * u_xlat1.x + u_xlat7.y;
        } else {
            u_xlat5.x = float(0.0);
            u_xlat5.y = float(0.0);
            u_xlat5.z = float(0.0);
            u_xlat3.x = 0.0;
            u_xlat2.x = 0.0;
        }
    } else {
        u_xlat5.x = float(0.0);
        u_xlat5.y = float(0.0);
        u_xlat5.z = float(0.0);
        u_xlat3.x = 0.0;
        u_xlat2.x = 0.0;
    }
    u_xlat1.xyz = u_xlat2.xxx * u_xlat5.xyz;
    u_xlat8.x = u_xlat1.y * u_xlat3.x;
    u_xlat1.xyz = u_xlat3.xxx * u_xlat1.xyz + u_xlat0.yzw;
    u_xlat3 = u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat3 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx + u_xlat3;
    u_xlat3 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz + u_xlat3;
    u_xlat3 = u_xlat3 + hlslcc_mtx4x4unity_MatrixVP[3];
    u_xlat4.xz = u_xlat3.xw * vec2(0.5, 0.5);
    u_xlat12 = u_xlat3.y * _ProjectionParams.x;
    u_xlat4.w = u_xlat12 * 0.5;
    vs_TEXCOORD1.yz = u_xlat4.zz + u_xlat4.xw;
    u_xlat4.xyz = u_xlat1.yyy * hlslcc_mtx4x4unity_MatrixV[1].xyz;
    u_xlat4.xyz = hlslcc_mtx4x4unity_MatrixV[0].xyz * u_xlat1.xxx + u_xlat4.xyz;
    u_xlat4.xyz = hlslcc_mtx4x4unity_MatrixV[2].xyz * u_xlat1.zzz + u_xlat4.xyz;
    vs_TEXCOORD5.xyz = u_xlat4.xyz + hlslcc_mtx4x4unity_MatrixV[3].xyz;
    gl_Position = u_xlat3;
    vs_TEXCOORD0.w = 1000.0;
    vs_TEXCOORD0.xyz = u_xlat0.xyw;
    vs_TEXCOORD1.x = 0.0;
    vs_TEXCOORD1.w = u_xlat3.w;
    vs_TEXCOORD2.xyz = u_xlat1.xyz;
    vs_TEXCOORD2.w = 0.0;
    vs_TEXCOORD3.xyz = in_POSITION0.xyz;
    u_xlat8.z = 0.0;
    vs_TEXCOORD4.xyz = u_xlat8.zzx;
    return;
}